services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./srcs/backend
    container_name: nest-backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./srcs/backend:/app
      - /app/node_modules
    expose:
      - "3000"
      - "51212"
    ports:
      - "51212:51212"
    networks:
      - net
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy

  frontend:
    build:
      context: ./srcs/frontend
    container_name: next-frontend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./srcs/frontend:/app
      - /app/node_modules
      - /app/.next
    expose:
      - "3000"
    networks:
      - net
    depends_on:
      postgres:
        condition: service_healthy

  localstack:
    container_name: localstack-s3
    image: localstack/localstack:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - SERVICES=s3
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - "localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4566/_localstack/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  nginx:
    build:
      context: ./srcs/nginx
    image: nginx
    container_name: nginx-server
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "9000:443"
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  postgres_data:
